### ISSUE TITLE
PHP Info (low warning) cause of missing Index

### ISSUE THREAD

**Issue by coolsurfer** [dmester/jdenticon-php#4] opened 2019-10-23 08:15 UTC
Canvas/Png/PngEncode.php Line 144 produces "Undefined offset" under some rare circumstances

Reproduce:
```
$ident  = new Jdenticon\Identicon(
    array(
        'style' => array(
            'backgroundColor' => '#FFFFFF00',
            'colorLightness' => array(0.00, 0.42),
            'grayscaleLightness' => array(0.00, 0.42),
            'colorSaturation' => 0.00,
            'grayscaleSaturation' => 0.00,
        ))
);
$ident->setValue('PR59358533')->setSize(500);
$ident->getImageData('png');
```

**my temporary (?) fix:**
`$colorIndex = ((isset($palette->lookup[$value])) ? $palette->lookup[$value] : 0);`

**Comment by dmester** [comment] 2019-11-02 11:51
Thanks for reporting this issue! The root cause was an index offset issue that kicked in when the PNG should have been encoded as a 32-bit PNG instead of an 8-bit PNG. A fix is included in version 1.0.0.

**Closed as completed by dmester** 2019-11-02 11:51 UTC
